name: Main

on:
  push:
    branches:
      - DevOps
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Upload Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET 8.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Publish
        run: dotnet publish -c Release -o out
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: api-build
          path: out
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download Build artifacts
        uses: actions/download-artifact@v4
        with:
          name: api-build
          path: out
      - name: Setup .NET 8.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      - name: Install dependencies
        run: dotnet restore
      - name: List Directory
        run: ls -R
  #     - name: Run Unit Tests
  #       run: dotnet test --no-build --verbosity quiet
  # integration-tests:
  #   name: Backend Integration Tests
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Download Build artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: api-build
  #         path: out
  #     - name: Setup .NET 8.x
  #       uses: actions/setup-dotnet@v3
  #       with:
  #         dotnet-version: '8.x'
  #     - name: Start API
  #       run: |
  #         dotnet out/GroceryStoreApi.dll &
  #         sleep 10
  #     - name: Install Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 20
  #     - name: Install Newman
  #       run: npm install -g newman
  #     - name: Run Newman
  #       run: newman run ./GroceryStoreTests/Integration/Postman/GroceryStoreAPI_Collections.json
