name: Unit Tests

on:
  workflow_run:
    workflows: ['Build Workflow']
    types: [completed]
    branches: [DevOps]

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET 8.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      - name: Install dependencies
        run: dotnet restore
      - name: List Directory
        run: ls -R
      - name: Run Unit Tests
        run: dotnet test --no-build --verbosity quiet
