name: main

on:
  push:
    branches:
      - DevOps
  pull_request:
    branches:
      - main

jobs:
  unit-test:
    name: Run Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET 8.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Run Unit Test
        run: dotnet test
      - name: Publish
        run: dotnet publish -c Release -o out
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: out
          path: out
  integration-test:
    name: Run Integration Test
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: out
          path: out
      - name: List artifact contents
        run: ls -lR
      - name: Start API
        run: |
          dotnet out/GroceryStoreApi.dll > api.log 2>&1 &
          echo $! > api_pid
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: List Directory
        run: ls -R
      - name: Install Newman
        run: npm install -g newman
      - name: check status of the api
        run: curl http://localhost:5000/status
      # - name: Run Integration tests
      #   run: newman run ./GroceryStoreTests/Integration/Postman/GroceryStoreAPI_Collections.json
